# Generated by Django 4.2.7 on 2023-11-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0004_alter_userinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
