# Generated by Django 4.2.7 on 2023-11-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonapp', '0005_userinfo_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='first_name',
        ),
    ]
